# Generated by Django 5.0 on 2026-06-03 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_building', models.CharField(max_length=120)),
                ('assigned_floor', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assigned_building', 'assigned_floor', 'user__username'],
                'indexes': [models.Index(fields=['assigned_building', 'assigned_floor'], name='accounts_st_assigne_c3292b_idx')],
            },
        ),
    ]
