# Generated by Django 5.0 on 2026-06-03 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_identifier', models.CharField(max_length=80, unique=True)),
                ('building', models.CharField(max_length=120)),
                ('floor', models.CharField(max_length=30)),
                ('room_number', models.CharField(blank=True, max_length=30)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['building', 'floor', 'camera_identifier'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=120)),
                ('floor', models.CharField(max_length=30)),
                ('room_number', models.CharField(max_length=30)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['building', 'floor', 'room_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'floor', 'room_number'), name='unique_room_location'),
        ),
        migrations.AddField(
            model_name='camera',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='monitor.room'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['building', 'floor'], name='monitor_cam_buildin_6c4671_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['camera_identifier'], name='monitor_cam_camera__2b1246_idx'),
        ),
    ]
